# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f091cb1ab30fe8483957f290965091d2857c9ccbd1df82cf0831a6781eed101ee0e16e33c012b64aaa32618e3222c46d099fc4c5b572a001714dc203c7c8e8a

test:
  secret_key_base: 9573a8480d4eeb85a792d700a42313fe349e4544b6b5638c60cf5e62f6c2ea9cef0797911c4bb03cb2c4a64c3920a05dc3fdbca85e567ad06d6dc37d3b206e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
